# Production configuration for subinc-cost-microservice

server:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 60s
  max_header_bytes: 1048576
  jobs_enabled: true

database:
  driver: postgres
  host: localhost
  port: 5432
  user: subinc
  password: postgres
  dbname: subinc_dev
  sslmode: disable
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: 30m

redis:
  host: localhost
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 0
  pool_size: 50
  min_idle_conns: 10
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

logging:
  level: info
  format: console
  color: true
  service: subinc-cost-microservice
  environment: production

aws:
  region: us-east-1
  cost_explorer_role_arn: "arn:aws:iam::123456789012:role/CostExplorerRole"
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  session_token: "${AWS_SESSION_TOKEN}"
# Add more sections as needed for SaaS features (webhooks, billing, etc.)

api:
  prefix: "/api/v1"
